[package]
name = "phraseforge"
version = "0.1.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
clap = "4.5.35"
directories = "6.0.0"
env_logger = "0.11.8"
log = "0.4.27"
rand = "0.9.0"
reqwest = { version = "0.11", features = ["blocking"] }
zip = "2.6.0"
